通过Pytorch进行激活函数的实现与计算

In [1]:
import torch.nn as nn
import torch
linear = nn.Linear(
    in_features=32, # 指定线性单元的输入维度
    out_features=2, # 指定线性单元的输出维度
)

In [2]:
# 初始化CUDA设备
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device.type

'cuda'

In [3]:
# 生成一个3x32的随机张量
inputs = torch.rand(3,32,device=device)
linear.to(device)
outputs = linear(inputs)

In [4]:
# 验证线性模型输出
outputs

tensor([[0.2776, 0.1083],
        [0.3354, 0.0144],
        [0.4595, 0.1812]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [5]:
# 通过调用nn.functional()类使用激活函数
activation_sigmoid = nn.functional.sigmoid(outputs)
activation_sigmoid
# 或者使用torch.sigmoid()直接进行调用（新版API）

/home/elin/anaconda3/lib/python3.9/site-packages/torch/nn/functional.py:1967: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


tensor([[0.5689, 0.5270],
        [0.5831, 0.5036],
        [0.6129, 0.5452]], device='cuda:0', grad_fn=<SigmoidBackward0>)

In [6]:
# 调用torch.softmax()执行softmax激活函数
activation_softmax = torch.softmax(outputs,dim=1)
activation_softmax

tensor([[0.5422, 0.4578],
        [0.5796, 0.4204],
        [0.5691, 0.4309]], device='cuda:0', grad_fn=<SoftmaxBackward0>)

In [7]:
# 同理调用relu
activation_relu = torch.relu(outputs)
activation_relu

tensor([[0.2776, 0.1083],
        [0.3354, 0.0144],
        [0.4595, 0.1812]], device='cuda:0', grad_fn=<ReluBackward0>)

通过继承`nn.Moudle`类实现自定的多层感知机

In [8]:
class MLP(nn.Module):
    def __init__(self,input_dim,hidden_dim,num_classes) -> None:
        """
        input_dim：指定多层感知机
        hidden_dim：指定隐藏层的输入大小，当使用多层Linear连接层时，该参数不该固定
        num_classes：指定最后的线性连接层的分类类别数量（即输出维度）
        """
        super(MLP,self).__init__()
        # 线性变换：输入层->隐藏层
        self.linear1 = nn.Linear(input_dim,hidden_dim)
        # 使用ReLu进行激活
        self.relu1 = torch.relu
        # 将隐含层线性变换为输出层
        self.linear2 = nn.Linear(hidden_dim,num_classes)
    def forward(self,inputs):
        hidden = self.linear1(inputs)
        activation = self.relu1(hidden)
        output = self.linear2(activation)
        probs = torch.softmax(outputs,dim=1)
        return probs

In [9]:
# 调用模型
mlp = MLP(input_dim=4,hidden_dim=5,num_classes=2)
# 生成随机输入张量
inputs = torch.rand(3,4)
# 计算该模型的多层感知结果
probs = mlp(inputs)
probs

tensor([[0.5422, 0.4578],
        [0.5796, 0.4204],
        [0.5691, 0.4309]], device='cuda:0', grad_fn=<SoftmaxBackward0>)