在Pytorch中使用LSTM模型

In [1]:
from torch.nn import LSTM
import torch

In [3]:
# 初始化CUDA设备
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device.type

'cuda'

In [7]:
# 初始一个LSTM层，输入维度为4，隐含层为5，开启batch_first
lstm = LSTM(4, 5, batch_first=True,device=device)
lstm

LSTM(4, 5, batch_first=True)

In [8]:
# 初始化输入数据，batch_size为2，序列长度为3，输入维度为4
inputs = torch.randn(2, 3, 4,device=device)
inputs

tensor([[[ 0.3375,  1.1748, -0.6476, -1.2820],
         [-1.7407,  1.5508,  1.1037,  0.8164],
         [ 0.3539, -1.0916, -0.2592, -0.0105]],

        [[-0.4913,  0.7585, -1.0887,  0.0504],
         [-0.0874,  1.1474, -0.9201,  1.2172],
         [ 0.9147,  0.1878,  0.4109,  0.8722]]], device='cuda:0')

In [9]:
outputs, (h_n, c_n) = lstm(inputs) # c_n为最后一个时间步的记忆细胞状态
outputs.shape, h_n.shape, c_n.shape

(torch.Size([2, 3, 5]), torch.Size([1, 2, 5]), torch.Size([1, 2, 5]))

In [10]:
outputs

tensor([[[-1.8937e-01, -5.7841e-02, -7.7918e-02, -1.0766e-01, -1.0654e-01],
         [-2.9439e-01, -2.0929e-01,  1.1267e-04, -7.8358e-02,  2.0115e-01],
         [-2.4992e-01,  6.0812e-03, -2.2275e-02, -1.3103e-01, -6.2236e-02]],

        [[-7.9335e-02, -9.5462e-02, -9.9495e-02, -1.4291e-01, -1.0712e-02],
         [ 3.4148e-02, -2.3240e-01, -1.3099e-01, -2.6577e-01,  4.2479e-02],
         [-1.0890e-01, -7.8834e-02,  4.3252e-02, -2.0739e-01, -2.9185e-02]]],
       device='cuda:0', grad_fn=<CudnnRnnBackward0>)

In [11]:
h_n

tensor([[[-0.2499,  0.0061, -0.0223, -0.1310, -0.0622],
         [-0.1089, -0.0788,  0.0433, -0.2074, -0.0292]]], device='cuda:0',
       grad_fn=<CudnnRnnBackward0>)

In [12]:
c_n

tensor([[[-0.5882,  0.0104, -0.0507, -0.2587, -0.1326],
         [-0.2125, -0.1021,  0.0794, -0.3683, -0.0386]]], device='cuda:0',
       grad_fn=<CudnnRnnBackward0>)